### PR TITLE
add gh builder action to build app

### PR DESCRIPTION
**Pull request by rohanshiva**
[ Sample action run](https://github.com/rohanshiva/gitgame/actions/runs/4393421520/jobs/7693804683)

### CODE REVIEW

**Comment by Ramko9999** [comment]
LGTM. I wonder if we should have 2 actions:

I think actions on feature-branch-push events should test whether the branch passes build tests. Build tests could be as simple as:
- Does the client and server on this branch build?
- Do the tests running on this branch? (I understand we don't have this at the moment).

I think actions on merge-to-master events extend feature-branch-push events by generating the built artifacts and pushing these artifacts to a production branch.

**Comment by rohanshiva** [comment]
Sounds good makes sense to me. Just to summarize your point:

One action to test feature branch builds. PR will only be able to merge into develop or master if the action passes.

Another action that runs on every merge to develop or master, builds the artifacts and then force pushes everything in develop including artifacts to production branch

**Comment by Ramko9999** [comment]
> Sounds good makes sense to me. Just to summarize your point:
> 
> One action to test feature branch builds. PR will only be able to merge into develop or master if the action passes.
> 
> Another action that runs on every merge to develop or master, builds the artifacts and then force pushes everything in develop including artifacts to production branch

Exactly

**Comment by Ramko9999** [comment]
Closing since #81

**Pull request closed without merging**
